src/main/java/com/heartfoilo/demo/config/WebConfig.java

:twisted_rightwards_arrows: Merge(feature/cors추가 -> dev): cors 허용 추가

---

src/main/java/com/heartfoilo/demo/domain/webSocket/handler/WebSocketClientHandler.java

:twisted_rightwards_arrows: Merge(feature/websocket -> dev): 주식 정보 발행 코드 추가

---

src/main/java/com/heartfoilo/demo/domain/stock/api/StockInformationController.java

:zap: Fix : StockInformationController 주석처리

:zap: Fix : StockInformationController 주석처리

---

src/main/java/com/heartfoilo/demo/domain/portfolio/repository/TotalAssetsRepository.java
src/main/java/com/heartfoilo/demo/domain/stock/dto/responseDto/GetAmountResponseDto.java
src/main/java/com/heartfoilo/demo/domain/stock/dto/responseDto/LikeStockResponseDto.java
src/main/java/com/heartfoilo/demo/domain/stock/dto/responseDto/PopularStockResponseDto.java
src/main/java/com/heartfoilo/demo/domain/stock/dto/responseDto/StockSearchResponseDto.java
src/main/java/com/heartfoilo/demo/domain/stock/service/LikeServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/stock/service/OrderServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/stock/service/PopularStockServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/stock/service/StockInfoServiceImpl.java
src/test/java/com/heartfoilo/demo/domain/stock/api/OrderControllerTest.java

- 인기 관심 주식 정보 한글 이름 추가
- 관심 종목 오류 수정
- 주식 정보 오류 수정

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 인기,관심 한글 이름 추가 및 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/stock/service/LikeServiceImpl.java

:twisted_rightwards_arrows: Merge(feature/stock Branch ->dev Branch): 관심종목 버그 수정

---

src/main/java/com/heartfoilo/demo/domain/webSocket/handler/WebSocketClientHandler.java

:twisted_rightwards_arrows: Merge(feature/소켓종목연결추가 -> dev): 소켓 연결 종목 추가

---

src/main/java/com/heartfoilo/demo/domain/portfolio/repository/PortfolioRepository.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetAssetsServiceImpl.java

:zap: Change: PortfolioRepository query 설정 변경 및 GetAssetsService 버그 수정
- 버그 발생으로 인한 긴급 PR

:zap: Change: PortfolioRepository query 설정 변경 및 GetAssetsService 버그 수정

---

src/main/java/com/heartfoilo/demo/config/WebConfig.java
src/main/java/com/heartfoilo/demo/domain/invest/repository/InvestRepository.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetInvestInfoServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetStocksServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetTotalStocksServiceImpl.java

:zap: Change: WebConfig 범위 변경 , /api/portfolio 제외 및 final 추가
- webConfig로 인한 접근 제한 및 코드오류 발생

:zap: Change: WebConfig 범위 변경 , /api/portfolio 제외 및 final 추가

---

src/main/java/com/heartfoilo/demo/config/WebConfig.java

:zap: Change: WebConfig portfolio 허용

:zap: Change: WebConfig portfolio 허용

---

src/main/java/com/heartfoilo/demo/config/WebConfig.java

:zap: Change: WebConfig에서 portfolio 제외

:zap: Change: WebConfig에서 portfolio 제외

---

src/main/java/com/heartfoilo/demo/Handler/HeartfolioInterceptor.java
src/main/java/com/heartfoilo/demo/config/WebConfig.java

:zap: Change : 핸들러 수정 및 WebConfig 재설정

:zap: Change : 핸들러 수정 및 WebConfig 재설정

---

src/main/java/com/heartfoilo/demo/domain/portfolio/entity/Account.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetAssetsServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/stock/api/OrderController.java
src/main/java/com/heartfoilo/demo/login/service/KakaoService.java

:zap: Change: 거래내역 조회 최신순부터 표기 및 신규 가입자 100만캐시 기부기능 추가
- 거래내역 표기가 보기 불편하다는 피드백 반영 , 신규 유저에게 지급하는 캐시기능 

:zap: Change: 거래내역 조회 최신순부터 표기 및 신규 가입자 100만캐시 기부기능 추가

---

src/main/java/com/heartfoilo/demo/Handler/HeartfolioInterceptor.java
src/main/java/com/heartfoilo/demo/domain/stock/api/OrderController.java

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 거래내역 오류 수정

---

src/main/java/com/heartfoilo/demo/config/WebConfig.java

:zap: Change: invest Domain WebConfig 영역 추가
- invest 기능 사용시 토큰에서 정보를 가져오기 위해서

:zap: Change: invest Domain WebConfig 영역 추가

---

src/main/java/com/heartfoilo/demo/domain/webSocket/handler/WebSocketClientHandler.java

:twisted_rightwards_arrows: Merge(feature/주식환율적용 -> dev): 주식 환율 적용

---

src/main/java/com/heartfoilo/demo/config/WebConfig.java
src/main/java/com/heartfoilo/demo/domain/invest/repository/OrderRepository.java
src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/repository/TotalAssetsRepository.java
src/main/java/com/heartfoilo/demo/domain/stock/repository/StockRepository.java

:twisted_rightwards_arrows: Merge(feature/invest -> Dev Branch): Refactor: 매수/매도 버그 수정
- 매수 매도가 안돼용 

:zap: Refactor: 매수/매도 버그 수정

---

src/main/java/com/heartfoilo/demo/Application.java
src/main/java/com/heartfoilo/demo/config/WebSocketClientConfig.java
src/main/java/com/heartfoilo/demo/domain/webSocket/dto/StockSocketInfoDto.java
src/main/java/com/heartfoilo/demo/domain/webSocket/handler/WebSocketClientHandler.java
src/main/java/com/heartfoilo/demo/dto/RequestOauthDto.java
src/main/java/com/heartfoilo/demo/util/RedisUtil.java
src/main/java/com/heartfoilo/demo/util/StockInfoPollingScheduler.java

- 주식 정보 요청 polling 스케쥴러 추가
- 1초에 2개 요청 제한이라 0.5초마다 하나씩 요청 후 레디스에 값 저장
- 환율 적용 (고정 환율 => Rest API 응답으로 오는 환율값 적용)

:twisted_rightwards_arrows: Merge(feature/polling스케쥴링 -> dev): 주식정보 polling 스케쥴러 추가

---

src/main/java/com/heartfoilo/demo/Handler/HeartfolioInterceptor.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetAssetsServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetInvestInfoServiceImpl.java
src/main/java/com/heartfoilo/demo/login/Entity/RefreshToken.java
src/main/java/com/heartfoilo/demo/login/Generator/JwtTokenProvider.java
src/main/java/com/heartfoilo/demo/login/Repository/RefreshTokenRepository.java
src/main/java/com/heartfoilo/demo/login/controller/RefreshTokenController.java
src/main/java/com/heartfoilo/demo/login/service/KakaoService.java
src/main/java/com/heartfoilo/demo/login/service/RefreshTokenService.java

:sparkles: Feat: accessToken 만료시 refreshToken을 통한 재발급 추가, 거래내역 정렬 추가
- 토큰 문제 해결 및 거래내역 최신순부터 나타나게 수정

:sparkles: Feat: accessToken 만료시 refreshToken을 통한 재발급 추가, 거래내역 정렬 추가

---

src/main/java/com/heartfoilo/demo/Handler/HeartfolioInterceptor.java
src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetAssetsServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetTotalStocksServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/webSocket/dto/StockSocketInfoDto.java

:twisted_rightwards_arrows: Merge(Source Branch -> Target Branch): 토큰만료 임시 주석처리 및 비회원 정보 조회기능
- 제목과 동일

:memo: Refactor : 토큰만료 임시 주석처리 및 비회원 정보 조회기능

---

src/main/java/com/heartfoilo/demo/Handler/HeartfolioInterceptor.java

- 비회원 주식 조회 오류 수정 유효하지 않은 토큰일 시 에러 반환 대신 userId null로 설정

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 비회원 주식조회 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java

:twisted_rightwards_arrows: Merge(feature/invest -> Target Branch): :zap: Refactor: 매수 오류 수정
- 매수 기능 버그 개선

:twisted_rightwards_arrows: Merge: 매수 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/webSocket/dto/StockSocketInfoDto.java

- api에서 제공하는 전일대비 수익이 0으로 표시되는 문제 => 현재 값 기준으로 전일 종가와 비교하여 수익, 수익률 저장하는 방식으로 변경

:twisted_rightwards_arrows: Merge(feature/stockInfo수정 -> dev): 전일대비 수익, 수익률 계산

---

src/main/java/com/heartfoilo/demo/Application.java
src/main/java/com/heartfoilo/demo/domain/news/api/NewsController.java
src/main/java/com/heartfoilo/demo/domain/news/dto/responseDto/NewsItemDto.java
src/main/java/com/heartfoilo/demo/domain/news/dto/responseDto/NewsResponseDto.java
src/main/java/com/heartfoilo/demo/domain/news/service/ApiSearchNewsService.java

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 뉴스 기능 구현

---

src/main/java/com/heartfoilo/demo/domain/stock/repository/StockRepository.java
src/main/java/com/heartfoilo/demo/domain/stock/service/OrderServiceImpl.java
src/main/java/com/heartfoilo/demo/util/StockInfoPollingScheduler.java

 :twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 종목 검색 오류 수정

---

src/main/java/com/heartfoilo/demo/Handler/HeartfolioInterceptor.java

:twisted_rightwards_arrows: Merge(feature/invest-> dev): 핸들러 수정

🔀 Merge(feature/invest-> dev): 핸들러 수정

---

src/main/java/com/heartfoilo/demo/Handler/HeartfolioInterceptor.java

:twisted_rightwards_arrows: Merge(feature/invest-> dev): Interceptor true 반환으로 변경

:twisted_rightwards_arrows: Merge(feature/invest-> dev): Interceptor true 반환으로 변경

---

src/main/java/com/heartfoilo/demo/domain/news/dto/responseDto/NewsItemDto.java
src/main/java/com/heartfoilo/demo/domain/news/service/ApiSearchNewsService.java

:twisted_rightwards_arrows: Merge(Source Branch -> Target Branch): 뉴스 날짜 데이터 수정 및 캐시 삭제

---

src/main/java/com/heartfoilo/demo/domain/news/service/ApiSearchNewsService.java
src/main/java/com/heartfoilo/demo/dto/DailyNewsDto.java
src/main/java/com/heartfoilo/demo/util/RedisUtil.java

:twisted_rightwards_arrows: Merge(feature/news캐싱 -> dev): 뉴스 캐싱

---

src/main/java/com/heartfoilo/demo/Application.java
src/main/java/com/heartfoilo/demo/domain/news/service/ApiSearchNewsService.java
src/main/java/com/heartfoilo/demo/util/StockInfoPollingScheduler.java

:twisted_rightwards_arrows: Merge(feature/stock Branch -> de Branch): HTML 태그 필터링 추가

---

src/main/java/com/heartfoilo/demo/domain/donation/api/LocalHomeController.java
src/main/java/com/heartfoilo/demo/domain/donation/api/PaymentController.java

:twisted_rightwards_arrows: Merge(feature/donation -> dev): @Cors 오류 방지
CORS 오류 방지

:zap: Refactor : CORS 오류 수정을 위해 @CrossOrigin 추가

---

src/main/java/com/heartfoilo/demo/domain/news/service/ApiSearchNewsService.java

- 부하테스트 결과 news API 오류 80% 정도 나옴. 매번 외부 API 호출하고 있어서 Redis 캐시로 활용했는데 응답시간 더 느려짐 + 다른 API도 오류 발생함. 다시 캐싱 제거 후 테스트 할 에정

:twisted_rightwards_arrows: Merge(feature/Redis캐싱제거 -> dev): 뉴스 캐싱 제거

---

src/main/java/com/heartfoilo/demo/domain/donation/api/LocalHomeController.java

:twisted_rightwards_arrows: Merge(feature/donation-> dev): 결제 컨트롤러 응답형식 JSON으로 변경
프론트엔드와 통신을 위한 응답 형식 변경

:twisted_rightwards_arrows: Merge(feature/donation-> dev): 결제 컨트롤러 응답형식 JSON으로 변경

---

src/main/java/com/heartfoilo/demo/domain/donation/api/LocalHomeController.java
src/main/java/com/heartfoilo/demo/domain/donation/service/PaymentServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/entity/Account.java

:twisted_rightwards_arrows: Merge(feature/donation -> dev): 캐시충전 성공시 유저에게 캐시 지급 로직 추가
- 유저에게 돈 지급 로직 필요

:twisted_rightwards_arrows: Merge(feature/donation -> dev): 캐시충전 성공시 유저에게 캐시 지급 로직 추가

---

src/main/java/com/heartfoilo/demo/domain/donation/service/PaymentServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/entity/Account.java
src/main/java/com/heartfoilo/demo/domain/portfolio/entity/TotalAssets.java

:twisted_rightwards_arrows: Merge(feature/donation -> dev): Entity Setter 제거
Entity 내 Setter 사용 지양

:twisted_rightwards_arrows: Merge(feature/donation -> dev): Entity Setter 제거

---

src/main/java/com/heartfoilo/demo/config/WebConfig.java

:twisted_rightwards_arrows: Merge(feature/info -> dev): user 관련 로직 핸들러 추가
- 핸들러 미적용시 401 에러

:twisted_rightwards_arrows: Merge(feature/info -> dev): user 관련 로직 핸들러 추가

---

src/main/java/com/heartfoilo/demo/config/WebConfig.java
src/main/java/com/heartfoilo/demo/domain/donation/service/PaymentServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/entity/Account.java
src/main/java/com/heartfoilo/demo/domain/user/service/UserServiceImpl.java

:twisted_rightwards_arrows: Merge(feature/info -> dev): 마이페이지 오류로 인한 리팩토링

---

src/main/java/com/heartfoilo/demo/config/RedisConfig.java
src/main/java/com/heartfoilo/demo/domain/news/service/ApiSearchNewsService.java

- 레디스 클러스터 구축 후 연결
- 뉴스 api 캐싱 추가

:twisted_rightwards_arrows: Merge(feature/redis클러스터링 -> dev): Redis 클러스터링

---

src/main/java/com/heartfoilo/demo/domain/donation/service/PaymentServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/entity/Account.java
src/main/java/com/heartfoilo/demo/domain/user/api/UserController.java
src/main/java/com/heartfoilo/demo/domain/user/repository/UserRepository.java
src/main/java/com/heartfoilo/demo/domain/user/service/UserService.java
src/main/java/com/heartfoilo/demo/domain/user/service/UserServiceImpl.java

닉네임 중복검사 로직 필요 및 로그아웃시 refreshToken 제거

:twisted_rightwards_arrows: Merge(feature/info-> dev): 닉네임 중복검사 로직 추가 및 로그아웃시 RefreshToken 제거

---

src/main/java/com/heartfoilo/demo/domain/donation/service/PaymentServiceImpl.java

:twisted_rightwards_arrows: Merge(feature/info -> dev): account ChangeCash 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/portfolio/entity/Account.java

:twisted_rightwards_arrows: Merge(feature/invest -> dev): 매수/매도 총매수금액 오류 수정

---

src/main/java/com/heartfoilo/demo/config/SchedulerConfig.java
src/main/java/com/heartfoilo/demo/domain/donation/service/PaymentServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/ranking/entity/Ranking.java
src/main/java/com/heartfoilo/demo/domain/ranking/repository/RankingRepository.java
src/main/java/com/heartfoilo/demo/domain/ranking/service/RankScheduler.java
src/main/java/com/heartfoilo/demo/domain/ranking/service/RankServiceImpl.java

:twisted_rightwards_arrows: Merge(Source Branch -> Target Branch): 랭킹 수익률 수정

---

src/main/java/com/heartfoilo/demo/domain/donation/service/DonationServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/donation/service/PaymentServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/ranking/entity/Ranking.java

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 기부 수익률 버그 수정

---

src/main/java/com/heartfoilo/demo/domain/ranking/service/RankServiceImpl.java

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 랭킹 이름 닉네임으로 변경

---

src/main/java/com/heartfoilo/demo/domain/ranking/dto/responseDto/RankingDonationResponseDto.java
src/main/java/com/heartfoilo/demo/domain/ranking/dto/responseDto/RankingResponseDto.java
src/main/java/com/heartfoilo/demo/domain/ranking/repository/RankingRepository.java
src/main/java/com/heartfoilo/demo/domain/ranking/service/RankServiceImpl.java

- 랭킹 데이터 userId 추가, 내 순위 오류 수정

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 랭킹 데이터 userId 추가, 내 순위 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/ranking/repository/RankingRepository.java

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 기부 랭킹 버그 수정

---

.gitignore
src/main/java/com/heartfoilo/demo/Handler/HeartfolioInterceptor.java
src/main/java/com/heartfoilo/demo/domain/portfolio/api/GetAssetsController.java
src/main/java/com/heartfoilo/demo/domain/portfolio/api/GetInvestInfoController.java
src/main/java/com/heartfoilo/demo/domain/portfolio/api/GetStocksController.java
src/main/java/com/heartfoilo/demo/domain/portfolio/api/GetTotalStocksController.java

:twisted_rightwards_arrows: Merge(feature/invest -> dev): 유저 캐시 조회시 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/api/GetAssetsController.java

:twisted_rightwards_arrows: Merge(feature/invest -> dev): 매수/매도시 Redis 가격과 비교로직 추가(버그 수정)

---

src/main/java/com/heartfoilo/demo/domain/stock/service/PopularStockServiceImpl.java
src/main/java/com/heartfoilo/demo/dto/DailyNewsDto.java

:twisted_rightwards_arrows: Merge(Source Branch -> Target Branch): 뉴스, 인기종목 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/stock/service/PopularStockServiceImpl.java

:twisted_rightwards_arrows: Merge(feature/rank Branch -> dev Branch): 인기 종목 버그 수정

---

build.gradle
src/main/java/com/heartfoilo/demo/domain/news/service/ApiSearchNewsService.java

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 중복 뉴스 제거

---

src/main/java/com/heartfoilo/demo/domain/fortune/api/FortuneController.java

- 프론트 요청 ) 인증 없이 운세조회 할 경우 그냥 null 값으로 응답 수정

:twisted_rightwards_arrows: Merge(feature/fortune -> dev): 운세정보 조회 인증없이 가능 수정

---

src/main/java/com/heartfoilo/demo/domain/news/service/ApiSearchNewsService.java

:twisted_rightwards_arrows: Merge(feature/stock Branch -> dev Branch): 중복 뉴스 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetStocksService.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetStocksServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetTotalStocksService.java
src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetTotalStocksServiceImpl.java

- []  feature 병합(feature issue #를 남겨주세요)
오류 해결 (반환 형식이 안맞아서 출력값이 안나옴)

:twisted_rightwards_arrows: Merge(feature/portfolio -> dev):  리팩토링 과정에서 반환 형식으로 인한 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/portfolio/service/GetStocksServiceImpl.java

:twisted_rightwards_arrows: Merge(feature/portfolio -> dev): GetStocks 반환형식 변경

---

src/main/java/com/heartfoilo/demo/domain/fortune/entity/DailyFortune.java
src/main/java/com/heartfoilo/demo/domain/fortune/service/FortuneServiceImpl.java

- 데일리 운세 등록 시 기존 등록된 운세 있으면 그거 업데이트 하도록 수정. 데일리 운세랑 유저 1대1 관계 유지.

:twisted_rightwards_arrows: Merge(fix/fortune중복등록 -> dev): 운세 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/portfolio/api/GetTotalStocksController.java

:twisted_rightwards_arrows: Merge(feature/portfolio -> dev):  userId 변환 오류 해결

---

src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/ranking/entity/Ranking.java
src/main/java/com/heartfoilo/demo/domain/ranking/repository/RankingRepository.java
src/main/java/com/heartfoilo/demo/domain/ranking/service/RankServiceImpl.java
src/main/java/com/heartfoilo/demo/util/StockInfoPollingScheduler.java

:twisted_rightwards_arrows: Merge(Source Branch -> Target Branch): 사용자 랭크 버그 수정

---

src/main/java/com/heartfoilo/demo/config/RedisConfig.java
src/main/java/com/heartfoilo/demo/util/RedisUtil.java

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX14VKvbeGUzNmExrAKGLf6rWP7wXYmNpgI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2sTXXzC)
- Redis 동시 접근할 때 에러 발생 문제 . 뉴스 조회 500에러 해결
- Redis 템플릿 분리

:twisted_rightwards_arrows: Merge(fix/redis동시접근에러 -> dev): Redis 템플릿 분리

---

src/main/java/com/heartfoilo/demo/util/develop/StockInfoPollingScheduler.java
src/main/java/com/heartfoilo/demo/util/develop/StockInfoPollingScheduler2.java
src/main/java/com/heartfoilo/demo/util/develop/StockInfoPollingScheduler3.java
src/main/java/com/heartfoilo/demo/util/develop/StockInfoPollingScheduler4.java
src/main/java/com/heartfoilo/demo/util/release/StockInfoPollingScheduler.java
src/main/java/com/heartfoilo/demo/util/release/StockInfoPollingScheduler2.java
src/main/java/com/heartfoilo/demo/util/release/StockInfoPollingScheduler3.java
src/main/java/com/heartfoilo/demo/util/release/StockInfoPollingScheduler4.java

:twisted_rightwards_arrows: Merge(feat/주식API키분리 -> dev): 주식 API 요청 분리

---

src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java

- 주식 매도 했을 때 -수익률 일 때 수익률 계산이 잘못되는 오류 수정

:twisted_rightwards_arrows: Merge(feature/rank Branch -> dev Branch): 랭킹 -수익률 오류 수정

---

src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java
src/main/java/com/heartfoilo/demo/domain/portfolio/entity/Account.java

산 금액만큼을 - 해줬는데 , 이것을 매수시 가격 기반으로 변경

:twisted_rightwards_arrows: Merge(feature/portfolio-> dev): 매도시 총매수금액 오류 해결

---

src/main/java/com/heartfoilo/demo/domain/portfolio/entity/Account.java

산 금액만큼을 - 해줬는데 , 이것을 매수시 가격 기반으로 변경

:twisted_rightwards_arrows: Merge(feature/portfolio-> dev): 총매수금액 오류 재수정

---

src/main/java/com/heartfoilo/demo/domain/invest/service/InvestServiceImpl.java

산 금액만큼을 - 해줬는데 , 이것을 매수시 가격 기반으로 변경
매수도 해결

:twisted_rightwards_arrows: Merge(feature/portfolio-> dev): 총매수금액 최종수정
